frontend:
  image: tutum/hipache
  ports:
    - "80:80"
    - "6379:6379"

app:
  build: .
  environment:
    - DOMAIN=local.docker
  links:
    - db
    - frontend
  volumes:
    - .:/myapp
  ports:
    - '3000'

db:
  image: mysql:5.7.8
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql

  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
