# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

production:
  adapter: mysql2
  database: sg_meetup
  min_messages: WARNING
  pool: 5
  username: root
  password: <%= ENV['RAILSDOCKER_DB_1_ENV_MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['RAILSDOCKER_DB_1_PORT_3306_TCP_ADDR'] %>
  port: <%= ENV['RAILSDOCKER_DB_1_PORT_3306_TCP_PORT'] %>